[build]
  command = "npm run build:client"
  publish = "dist/spa"
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"
  included_files = ["server/**", "shared/**"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"