[build]
  # Build the server first, then the client
  command = "npm run build:server && npm run build:client"
  publish = "dist/spa"
  # Point to the directory with the bundled function
  functions = "netlify/functions-dist"

# We no longer need the [functions] section as the defaults will work

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"